// <auto-generated />
namespace SuperShoes.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changeofthedatatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changeofthedatatype));
        
        string IMigrationMetadata.Id
        {
            get { return "201702191411213_Change of the data type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
