// <auto-generated />
namespace SuperShoes.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewfieldinArticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewfieldinArticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201702191441320_New field in Article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
